### PR TITLE
Add zuul playbook to project

### PR DESCRIPTION
**Pull request by bagaswibowo25**

### CODE REVIEW

**Comment by bagaswibowo25** [comment]
recheck

**Comment by bagaswibowo25** [comment]
recheck

**Comment by bagaswibowo25** [comment]
recheck

**Comment by bagaswibowo25** [comment]
recheck

**Comment by bagaswibowo25** [comment]
recheck

**Comment by bagaswibowo25** [comment]
recheck

**Comment by bagaswibowo25** [comment]
recheck

**Comment by bagaswibowo25** [comment]
recheck

**Comment by bagaswibowo25** [comment]
recheck

**Comment by bagaswibowo25** [comment]
recheck

**Comment by bagaswibowo25** [comment]
recheck

**Comment by bagaswibowo25** [comment]
recheck

**Comment by bagaswibowo25** [comment]
recheck

**Comment by bagaswibowo25** [comment]
recheck

**Comment by bagaswibowo25** [comment]
recheck

**Comment by bagaswibowo25** [comment]
regate

**Review by quirkymayer — APPROVED** [review]
lgtm

**Pull request merged**
